export type Mode = "couples" | "exes" | "strangers";
// what a game costs and therefore how long it is. free is the taster.
export type Tier = "free" | "paid";
export const MODES: { id: Mode; label: string; line: string }[] = [
  { id: "couples", label: "Couples", line: "warm. the things you assume they already know." },
  { id: "exes", label: "Exes", line: "honest. the things you never said out loud." },
  { id: "strangers", label: "Strangers", line: "playful. the things you'd say before you knew better." },
];
export const ROUNDS = ["before", "between", "again"];
export const PAID_PER_ROUND = 7;
export const FREE_COUNT = 5;
// 3 rounds x 7 cards. Cards starting with "dare:" are typed dares, never physical.
export const DECKS: Record<Mode, string[][]> = {
  couples: [
    [ // before
      "what did you notice about me first?",
      "what did you think i thought of you?",
      "what's a small thing i do that you'd miss?",
      "when did you first feel safe with me?",
      "what did you almost not tell me early on?",
      "dare: describe our first kiss in one sentence, no names.",
      "what did you think this would be, back then?",
      "when did you decide you wanted this?",
      "what did you lie about to seem better?",
      "who did you tell about me first, and what did you say?",
      "what were you sure i'd get bored of?",
      "what did you rehearse before you said it?",
      "dare: text me the first photo of us on your phone.",
      "what did your friends think of me at the start?",
      "what did i do that you found embarrassing and kept quiet about?",
      "what were you scared i'd find out?",
      "what were you doing the week before we met?",
      "when did you stop performing around me?",
      "dare: write the first message you wish you'd sent.",
      "what did you notice that you've never mentioned?",
      "what did you think would be the problem, and was it?",
    ],
    [ // between
      "what's something i did that hurt and you never said?",
      "when did you feel furthest from me?",
      "what do you protect me from knowing?",
      "what do i get wrong about you?",
      "what's the fight we keep having, underneath?",
      "dare: send the last photo of us you didn't delete.",
      "what do you need more of from me? one thing.",
      "what do you do when you're upset that i never notice?",
      "what have you given up for this without saying?",
      "when did you last lie to keep the peace?",
      "what do i do that makes you feel small?",
      "what's the thing you've decided not to ask me?",
      "dare: describe our worst night in one sentence, no blame.",
      "what would you change about me if you could, honestly?",
      "when did you last feel proud of me and not say it?",
      "what do you think i'm scared of?",
      "what part of me do you find hardest to love?",
      "what do you pretend to like for me?",
      "dare: write the sentence you swallowed this week.",
      "what have i stopped doing that you miss?",
      "where do you go in your head when we argue?",
    ],
    [ // again
      "if we met today, would you say hey?",
      "what's the version of us you're afraid of?",
      "what's the version of us you want?",
      "what do you still not believe about me?",
      "what will you remember about this year?",
      "dare: write the text you'd send me if i moved away tomorrow.",
      "say the thing. the one you've been holding.",
      "what do you want from the next five years that you haven't said out loud?",
      "what would you need to hear to feel sure?",
      "what are you still waiting for me to do?",
      "what would break this, if anything?",
      "dare: write my name and one sentence about who i am to you.",
      "what do you hope i never stop doing?",
      "what have you forgiven me for without telling me?",
      "what do you want to be true about us in ten years?",
      "what are you afraid to want?",
      "dare: describe the life you'd pick for us, in one line.",
      "what do you think we're avoiding?",
      "what would you do differently if you knew it lasts?",
      "what do you need me to know before tonight ends?",
      "what's the promise you'd make right now and keep?",
    ],
  ],
  exes: [
    [ // before
      "what did you notice about me first?",
      "what did you tell your friends about me?",
      "what's the moment you knew?",
      "what did i get right, at the start?",
      "what did you pretend not to see?",
      "dare: describe the last good day in one sentence.",
      "what did you think this would be, back then?",
      "when did you first think it wouldn't work?",
      "what did you love that you'd never admit now?",
      "what did you want me to be?",
      "who warned you about me?",
      "dare: name the song from that first month.",
      "what did you change about yourself for me?",
      "what did you think i saw in you?",
      "what were we both pretending, early on?",
      "what's the memory you go back to?",
      "what did you brag about?",
      "dare: write the first text you ever sent me, from memory.",
      "when were you happiest with me?",
      "what did you think i'd become?",
      "what did you ignore because it was good otherwise?",
    ],
    [ // between
      "what's something i did that hurt and you never said?",
      "when did it actually end for you?",
      "what did you lie about?",
      "what do you think i lied about?",
      "what did you keep of mine?",
      "dare: send the last photo of us you didn't delete.",
      "what would you have done differently? one thing.",
      "what was the last straw, really?",
      "who did you talk to about us, and what did you say?",
      "what did you blame me for that wasn't mine?",
      "what did i do that you've never told anyone?",
      "when did you stop trying?",
      "dare: describe the night it turned, in one sentence.",
      "what were you doing while i thought we were fine?",
      "what did you need that i couldn't give?",
      "what's the cruellest thing you thought and didn't say?",
      "what part of it was your fault?",
      "dare: write the apology you never sent.",
      "what did you tell yourself to get through it?",
      "what did you miss first?",
      "what did you hope i'd do, and i didn't?",
    ],
    [ // again
      "if we met today, would you say hey?",
      "what do you still not believe about me?",
      "what are you grateful i did?",
      "what are you grateful you left?",
      "what do you hope i think of you?",
      "dare: write the text you almost sent and deleted.",
      "say the thing. the one you've been holding.",
      "should we get back together?",
      "what would have to be different?",
      "do you still think about it? honestly.",
      "what did i teach you that you still use?",
      "dare: write what you'd say at my wedding.",
      "what do you want me to know about your life now?",
      "who did you become after?",
      "would you do it again, knowing how it ends?",
      "what do you owe me, if anything?",
      "dare: describe me to a stranger in one sentence.",
      "what are you still angry about?",
      "what do you forgive me for, now?",
      "is there a version of this where we're friends?",
      "what do you hope happens to me?",
    ],
  ],
  strangers: [
    [ // before
      "what did you notice about me first?",
      "what's a thing you assumed about me?",
      "what do people get wrong about you?",
      "what's your most on-purpose habit?",
      "what would your 16-year-old self say about tonight?",
      "dare: describe me in three words, no compliments.",
      "what did you think this would be, back then?",
      "what did you decide about me before i spoke?",
      "what's the story you tell at parties?",
      "what do you want people to notice first?",
      "what are you pretending to be relaxed about?",
      "dare: guess my last search and say it out loud.",
      "what's a compliment you never believe?",
      "what did you nearly say instead of hello?",
      "what would your friends say i'm like?",
      "what's the last risk you took?",
      "what do you do when you don't know anyone?",
      "dare: describe your week in one honest sentence.",
      "what are you better at than you admit?",
      "what's the first lie you tell new people?",
      "what were you hoping tonight would be?",
    ],
    [ // between
      "what's a thing you stopped telling people?",
      "when did you last feel like a kid?",
      "what's the idea you shelved?",
      "what are you avoiding this week?",
      "who did you stop texting on purpose?",
      "dare: send a photo of the room you're in, no cleaning up.",
      "what do you need more of? one thing.",
      "what do you do that you'd be embarrassed for me to see?",
      "when did you last cry, and why?",
      "what did you want at twelve that you still want?",
      "who do you miss and haven't told?",
      "dare: read out the last thing you typed and deleted.",
      "what's the thing you're bad at that you keep doing?",
      "what are you tired of explaining?",
      "what would you do with a free year?",
      "what do you spend money on to feel better?",
      "what's the compliment you'd like and never get?",
      "dare: name the person you'd call at 3am, and why them.",
      "what have you never told anyone here?",
      "what do you lie about on forms?",
      "what are you pretending not to care about?",
    ],
    [ // again
      "if we met again in five years, would you say hey?",
      "what are you scared you'll become?",
      "what are you scared you won't?",
      "what do you want me to remember about you?",
      "what will you remember about this?",
      "dare: write the text you'd send me tomorrow morning.",
      "say the thing. the one you've been holding.",
      "what do you think i've got wrong about you tonight?",
      "what would you change about your life this year?",
      "what do you want to be true by next birthday?",
      "who do you want to be to the people who know you?",
      "dare: write the advice you'd give yourself a year ago.",
      "what's the thing you'd do if nobody found out?",
      "what do you want someone to ask you?",
      "what would you do if you weren't scared of it?",
      "what's the life you almost chose?",
      "dare: describe tonight to someone who wasn't here.",
      "what do you want more of, and what's stopping you?",
      "what's the hardest true thing about you?",
      "would you tell me something you've never said out loud?",
      "what do you hope i think about you after this?",
    ],
  ],
};

// The free five. Deliberately the shallow end: enough to teach the mechanic
// (both answer in secret, both reveal at once, nobody can edit after seeing)
// without giving away the cards people pay for. Fixed, same for everyone, and
// never drawn into a paid game, so buying is never a card you have already had.
export const FREE: Record<Mode, string[]> = {
  couples: [
    "what did i wear the day we met?",
    "what song makes you think of me?",
    "what's my worst habit, honestly?",
    "where would you take me with no notice?",
    "what do you think i'd say if someone asked about you?",
  ],
  exes: [
    "what's the first thing you'd say if we met today?",
    "what song did you skip for a while after?",
    "what did you tell people about why it ended?",
    "what's one thing you'd still thank me for?",
    "what do you think i say about you now?",
  ],
  strangers: [
    "what did you assume about me in the first ten seconds?",
    "what do you think i do for work?",
    "what would you order for me?",
    "what's your most useless talent?",
    "what's a question you wish people asked you?",
  ],
};
